dist: xenial
notifications:
  email: false
git:
  quiet: true
  depth: 1
env:
  global:
  - TERM=dumb
language: java
jdk: openjdk8
install: true
script: ./mvnw clean test -U
cache:
  directories:
  - ~/.m2
